CREATE TABLE cliente (
    idCliente INT PRIMARY KEY,
    nombreCliente VARCHAR(100) NOT NULL,
    apellidoCliente VARCHAR(100) NOT NULL,
    correoCliente VARCHAR(150) NOT NULL UNIQUE,
    telefonoCliente VARCHAR(20) NOT NULL
);

CREATE TABLE direccion_cliente (
    idDireccion INT PRIMARY KEY,
    direccionCliente VARCHAR(200) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    idCliente INT NOT NULL,
    CONSTRAINT fk_direccion_cliente_cliente
        FOREIGN KEY (idCliente) REFERENCES cliente(idCliente)
);

CREATE TABLE empleado (
    idEmpleado INT PRIMARY KEY,
    nombreEmpleado VARCHAR(100) NOT NULL,
    apellidoEmpleado VARCHAR(100) NOT NULL,
    puesto VARCHAR(100) NOT NULL
);

CREATE TABLE categoria (
    idCategoria INT PRIMARY KEY,
    nombreCategoria VARCHAR(100) NOT NULL,
    descripcionCategoria VARCHAR(200) NOT NULL
);

CREATE TABLE proveedor (
    idProveedor INT PRIMARY KEY,
    nombreProveedor VARCHAR(150) NOT NULL,
    telefonoProveedor VARCHAR(20) NOT NULL,
    correoProveedor VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE producto (
    idProducto INT PRIMARY KEY,
    nombreProducto VARCHAR(150) NOT NULL,
    precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0),
    stock INT NOT NULL CHECK (stock >= 0),
    idCategoria INT NOT NULL,
    idProveedor INT NOT NULL,
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (idCategoria) REFERENCES categoria(idCategoria),
    CONSTRAINT fk_producto_proveedor
        FOREIGN KEY (idProveedor) REFERENCES proveedor(idProveedor)
);

CREATE TABLE inventario_movimiento (
    idMovimiento INT PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('entrada', 'salida')),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    fecha DATE NOT NULL,
    idProducto INT NOT NULL,
    CONSTRAINT fk_inventario_movimiento_producto
        FOREIGN KEY (idProducto) REFERENCES producto(idProducto)
);

CREATE TABLE venta (
    idVenta INT PRIMARY KEY,
    fecha DATE NOT NULL,
    total DECIMAL(10,2) NOT NULL CHECK (total >= 0),
    idCliente INT NOT NULL,
    idEmpleado INT NOT NULL,
    CONSTRAINT fk_venta_cliente
        FOREIGN KEY (idCliente) REFERENCES cliente(idCliente),
    CONSTRAINT fk_venta_empleado
        FOREIGN KEY (idEmpleado) REFERENCES empleado(idEmpleado)
);

CREATE TABLE detalle_venta (
    idDetalle INT PRIMARY KEY,
    idVenta INT NOT NULL,
    idProducto INT NOT NULL,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precioUnitario DECIMAL(10,2) NOT NULL CHECK (precioUnitario >= 0),
    subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (idVenta) REFERENCES venta(idVenta),
    CONSTRAINT fk_detalle_venta_producto
        FOREIGN KEY (idProducto) REFERENCES producto(idProducto)
);

CREATE TABLE metodo_pago (
    idMetodoPago INT PRIMARY KEY,
    tipoMetodoPago VARCHAR(50) NOT NULL
);

CREATE TABLE pago (
    idPago INT PRIMARY KEY,
    monto DECIMAL(10,2) NOT NULL CHECK (monto >= 0),
    fecha DATE NOT NULL,
    idVenta INT NOT NULL,
    idMetodoPago INT NOT NULL,
    CONSTRAINT fk_pago_venta
        FOREIGN KEY (idVenta) REFERENCES venta(idVenta),
    CONSTRAINT fk_pago_metodo_pago
        FOREIGN KEY (idMetodoPago) REFERENCES metodo_pago(idMetodoPago)
);

CREATE VIEW vista_ventas_completas AS
SELECT
    v.idVenta,
    v.fecha,
    c.nombreCliente || ' ' || c.apellidoCliente AS cliente,
    e.nombreEmpleado || ' ' || e.apellidoEmpleado AS empleado,
    v.total,
    mp.tipoMetodoPago AS metodoPago,
    p.monto AS montoPagado
FROM venta v
JOIN cliente c ON v.idCliente = c.idCliente
JOIN empleado e ON v.idEmpleado = e.idEmpleado
LEFT JOIN pago p ON v.idVenta = p.idVenta
LEFT JOIN metodo_pago mp ON p.idMetodoPago = mp.idMetodoPago;

CREATE TABLE usuario (
    idUsuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreUsuario VARCHAR(100) NOT NULL,
    correoUsuario VARCHAR(150) NOT NULL UNIQUE,
    passwordUsuario VARCHAR(100) NOT NULL,
    rol VARCHAR(50) NOT NULL DEFAULT 'vendedor'
);

ALTER TABLE usuario
ADD CONSTRAINT chk_usuario_rol
CHECK (rol IN ('administrador', 'gerente', 'vendedor', 'bodega', 'analista'));

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rol_administrador') THEN
        CREATE ROLE rol_administrador;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rol_gerente') THEN
        CREATE ROLE rol_gerente;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rol_vendedor') THEN
        CREATE ROLE rol_vendedor;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rol_bodega') THEN
        CREATE ROLE rol_bodega;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rol_analista') THEN
        CREATE ROLE rol_analista;
    END IF;
END
$$;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO rol_administrador, rol_gerente, rol_vendedor, rol_bodega, rol_analista;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM rol_administrador, rol_gerente, rol_vendedor, rol_bodega, rol_analista;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM rol_administrador, rol_gerente, rol_vendedor, rol_bodega, rol_analista;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO rol_administrador;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rol_administrador;

GRANT SELECT, INSERT, UPDATE, DELETE ON
    cliente,
    direccion_cliente,
    empleado,
    categoria,
    proveedor,
    producto,
    inventario_movimiento,
    venta,
    detalle_venta,
    metodo_pago,
    pago,
    usuario
TO rol_gerente;
GRANT SELECT ON vista_ventas_completas TO rol_gerente;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rol_gerente;

GRANT SELECT ON producto, categoria, proveedor, empleado, metodo_pago, vista_ventas_completas TO rol_vendedor;
GRANT SELECT, INSERT, UPDATE ON cliente, direccion_cliente TO rol_vendedor;
GRANT SELECT, INSERT ON venta, detalle_venta, pago, inventario_movimiento TO rol_vendedor;
GRANT UPDATE (stock) ON producto TO rol_vendedor;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rol_vendedor;

GRANT SELECT ON categoria, proveedor, producto, inventario_movimiento TO rol_bodega;
GRANT INSERT, UPDATE, DELETE ON producto TO rol_bodega;
GRANT INSERT ON inventario_movimiento TO rol_bodega;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rol_bodega;

GRANT SELECT ON
    cliente,
    direccion_cliente,
    empleado,
    categoria,
    proveedor,
    producto,
    inventario_movimiento,
    venta,
    detalle_venta,
    metodo_pago,
    pago,
    vista_ventas_completas
TO rol_analista;

GRANT rol_administrador TO proy3;
GRANT rol_gerente TO proy3;
GRANT rol_vendedor TO proy3;
GRANT rol_bodega TO proy3;
GRANT rol_analista TO proy3;
